openapi: 3.0.3
info:
  title: Sample Api Specification 2
  description: Sample Api Specification 2
  version: 1.0.0
servers:
  - url: 'localhost:8080/service2'
paths:
  /teams:
    get:
      summary: Get Teams
      operationId: listTeams
      tags:
        - team
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
components:
    schemas:
        Team:
          type: object
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string